using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using UnityEditor;

namespace Base.ToolPackage.Editor.CodebaseGraph.Scanning
{
    /// <summary>
    /// Maps types to the script file that declares them. MonoScript.GetClass only answers for the one
    /// type whose name matches the file name, and returns nothing at all for generics, so on its own it
    /// loses every nested type, every enum sharing a file and every generic class. A text pass over the
    /// same files fills those in, and notes which files came out of a generator while it is there.
    /// </summary>
    internal static class ScriptPathResolver
    {
        private const int HeaderWindow = 1200;
        private const string ScriptFilter = "t:MonoScript";
        private const string TypeDeclarationPattern = @"\b(?:class|struct|interface|enum|record)\s+@?(\w+)";

        /// <summary>Header text that marks a file as tool output rather than handwritten code.</summary>
        private static readonly string[] GeneratedHeaderMarkers =
        {
            "auto-generated",
            "autogenerated",
            "This code was generated",
            "This file was generated",
            "Generated by",
            "do not modify",
            "changes to this file may cause"
        };

        private static readonly Regex TypeDeclarationRegex = new(TypeDeclarationPattern, RegexOptions.Compiled);

        /// <summary>Lists every script asset in the project.</summary>
        /// <returns>The asset paths.</returns>
        public static List<string> CollectPaths()
        {
            List<string> paths = new();

            foreach (string guid in AssetDatabase.FindAssets(ScriptFilter))
                paths.Add(AssetDatabase.GUIDToAssetPath(guid));

            return paths;
        }

        /// <summary>Reads every script once and builds the whole index from it.</summary>
        /// <param name="paths">Every script asset in the project.</param>
        /// <param name="progress">Reporter that can also cancel the pass.</param>
        /// <returns>The index, or null when the scan was canceled.</returns>
        public static ScriptIndex Build(IReadOnlyList<string> paths, ScanProgress progress)
        {
            ScriptIndex index = new();

            for (int position = 0; position < paths.Count; position++)
            {
                IndexByMonoScript(paths[position], index);
                IndexBySourceText(paths[position], index);

                if (!progress.Report(position, paths.Count, "Reading scripts"))
                    return null;
            }

            return index;
        }

        private static void IndexByMonoScript(string path, ScriptIndex index)
        {
            MonoScript script = AssetDatabase.LoadAssetAtPath<MonoScript>(path);
            if (script == null)
                return;

            Type type = script.GetClass();
            if (type == null)
                return;

            index.ByFullName[TypeNameFormatter.FormatFullName(type)] = path;
        }

        private static void IndexBySourceText(string path, ScriptIndex index)
        {
            string source = ScriptSourceReader.Read(path);
            if (string.IsNullOrEmpty(source))
                return;

            index.Sources[path] = source;

            bool isGenerated = HasGeneratedHeader(source);
            if (isGenerated)
                index.GeneratedPaths.Add(path);

            foreach (Match match in TypeDeclarationRegex.Matches(source))
            {
                string name = match.Groups[1].Value;

                // The first file to declare a name wins, which keeps partial classes on their main file.
                index.BySimpleName.TryAdd(name, path);

                if (isGenerated)
                    index.GeneratedTypeNames.Add(name);
            }
        }

        private static bool HasGeneratedHeader(string source)
        {
            if (string.IsNullOrEmpty(source))
                return false;

            string header = source[..Math.Min(source.Length, HeaderWindow)];

            foreach (string marker in GeneratedHeaderMarkers)
            {
                if (header.IndexOf(marker, StringComparison.OrdinalIgnoreCase) >= 0)
                    return true;
            }

            return false;
        }
    }
}